2024-03-28 18:09:55,062 INFO    StreamThr :80421 [internal.py:wandb_internal():86] W&B internal server running at pid: 80421, started at: 2024-03-28 18:09:55.061371
2024-03-28 18:09:55,063 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status
2024-03-28 18:09:55,066 INFO    WriterThread:80421 [datastore.py:open_for_write():87] open: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/run-ob07yjgb.wandb
2024-03-28 18:09:55,067 DEBUG   SenderThread:80421 [sender.py:send():382] send: header
2024-03-28 18:09:55,097 DEBUG   SenderThread:80421 [sender.py:send():382] send: run
2024-03-28 18:09:55,474 INFO    SenderThread:80421 [dir_watcher.py:__init__():211] watching files in: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files
2024-03-28 18:09:55,474 INFO    SenderThread:80421 [sender.py:_start_run_threads():1136] run started: ob07yjgb with start time 1711663795.062209
2024-03-28 18:09:55,488 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: check_version
2024-03-28 18:09:55,489 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: check_version
2024-03-28 18:09:55,731 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: run_start
2024-03-28 18:09:55,732 DEBUG   HandlerThread:80421 [system_info.py:__init__():27] System info init
2024-03-28 18:09:55,732 DEBUG   HandlerThread:80421 [system_info.py:__init__():42] System info init done
2024-03-28 18:09:55,732 INFO    HandlerThread:80421 [system_monitor.py:start():194] Starting system monitor
2024-03-28 18:09:55,733 INFO    SystemMonitor:80421 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-03-28 18:09:55,733 INFO    HandlerThread:80421 [system_monitor.py:probe():214] Collecting system info
2024-03-28 18:09:55,733 INFO    SystemMonitor:80421 [interfaces.py:start():190] Started cpu monitoring
2024-03-28 18:09:55,735 INFO    SystemMonitor:80421 [interfaces.py:start():190] Started disk monitoring
2024-03-28 18:09:55,735 DEBUG   HandlerThread:80421 [system_info.py:probe():151] Probing system
2024-03-28 18:09:55,737 INFO    SystemMonitor:80421 [interfaces.py:start():190] Started gpuapple monitoring
2024-03-28 18:09:55,742 INFO    SystemMonitor:80421 [interfaces.py:start():190] Started memory monitoring
2024-03-28 18:09:55,743 INFO    SystemMonitor:80421 [interfaces.py:start():190] Started network monitoring
2024-03-28 18:09:55,749 DEBUG   HandlerThread:80421 [system_info.py:_probe_git():136] Probing git
2024-03-28 18:09:55,789 DEBUG   HandlerThread:80421 [system_info.py:_probe_git():144] Probing git done
2024-03-28 18:09:55,789 DEBUG   HandlerThread:80421 [system_info.py:probe():199] Probing system done
2024-03-28 18:09:55,789 DEBUG   HandlerThread:80421 [system_monitor.py:probe():223] {'os': 'macOS-14.3.1-arm64-arm-64bit', 'python': '3.8.18', 'heartbeatAt': '2024-03-28T22:09:55.737710', 'startedAt': '2024-03-28T22:09:55.052794', 'docker': None, 'cuda': None, 'args': ('--algorithm=BP', '--dataset=MNIST', '--learning_rate=0.1', '--stepsize=0.01', '--test', '--log', '--save=yes', '--epochs=10'), 'state': 'running', 'program': 'main.py', 'codePathLocal': 'main.py', 'codePath': 'CLtargetprop/main.py', 'git': {'remote': 'https://github.com/emmagg6/propagation.git', 'commit': '0526362cb18c91d4d47af1e47edd9078c265066b'}, 'email': '125744177+emmagg6@users.noreply.github.com', 'root': '/Users/emmagraham/Documents/GitHub/propagation', 'host': 'vpn-investment-office-231-132-23.dartmouth.edu', 'username': 'emmagraham', 'executable': '/Users/emmagraham/anaconda3/envs/target-prop/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'cpu_freq': {'current': 3504, 'min': 600, 'max': 3504}, 'cpu_freq_per_core': [{'current': 3504, 'min': 600, 'max': 3504}], 'disk': {'/': {'total': 926.3517189025879, 'used': 9.436077117919922}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 16.0}}
2024-03-28 18:09:55,790 INFO    HandlerThread:80421 [system_monitor.py:probe():224] Finished collecting system info
2024-03-28 18:09:55,790 INFO    HandlerThread:80421 [system_monitor.py:probe():227] Publishing system info
2024-03-28 18:09:55,790 DEBUG   HandlerThread:80421 [system_info.py:_save_conda():208] Saving list of conda packages installed into the current environment
2024-03-28 18:09:56,479 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/conda-environment.yaml
2024-03-28 18:09:56,603 DEBUG   HandlerThread:80421 [system_info.py:_save_conda():220] Saving conda packages done
2024-03-28 18:09:56,604 INFO    HandlerThread:80421 [system_monitor.py:probe():229] Finished publishing system info
2024-03-28 18:09:56,606 DEBUG   SenderThread:80421 [sender.py:send():382] send: files
2024-03-28 18:09:56,606 INFO    SenderThread:80421 [sender.py:_save_file():1403] saving file wandb-metadata.json with policy now
2024-03-28 18:09:56,611 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: python_packages
2024-03-28 18:09:56,611 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: python_packages
2024-03-28 18:09:56,611 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 18:09:56,612 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 18:09:56,612 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: stop_status
2024-03-28 18:09:56,896 DEBUG   SenderThread:80421 [sender.py:send():382] send: telemetry
2024-03-28 18:09:57,137 INFO    wandb-upload_0:80421 [upload_job.py:push():131] Uploaded file /var/folders/n8/ldy_g4ps26b_8kzptnbt6bww0000gn/T/tmp3guv64kdwandb/ri6ge4iv-wandb-metadata.json
2024-03-28 18:09:57,483 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/conda-environment.yaml
2024-03-28 18:09:57,483 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/wandb-metadata.json
2024-03-28 18:09:57,484 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/requirements.txt
2024-03-28 18:10:00,912 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:10:05,934 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:10:08,806 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: partial_history
2024-03-28 18:10:08,808 DEBUG   SenderThread:80421 [sender.py:send():382] send: history
2024-03-28 18:10:08,808 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: summary_record
2024-03-28 18:10:08,810 INFO    SenderThread:80421 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-28 18:10:09,541 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/output.log
2024-03-28 18:10:09,541 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/wandb-summary.json
2024-03-28 18:10:11,551 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/output.log
2024-03-28 18:10:11,617 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 18:10:11,617 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 18:10:11,617 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: stop_status
2024-03-28 18:10:11,779 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:10:16,794 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:10:21,807 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:10:22,535 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: partial_history
2024-03-28 18:10:22,536 DEBUG   SenderThread:80421 [sender.py:send():382] send: history
2024-03-28 18:10:22,536 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: summary_record
2024-03-28 18:10:22,537 INFO    SenderThread:80421 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-28 18:10:22,608 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/wandb-summary.json
2024-03-28 18:10:25,624 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/output.log
2024-03-28 18:10:26,660 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 18:10:26,661 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 18:10:26,661 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: stop_status
2024-03-28 18:10:26,852 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:10:27,637 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/config.yaml
2024-03-28 18:10:31,998 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:10:35,853 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: partial_history
2024-03-28 18:10:35,855 DEBUG   SenderThread:80421 [sender.py:send():382] send: history
2024-03-28 18:10:35,855 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: summary_record
2024-03-28 18:10:35,857 INFO    SenderThread:80421 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-28 18:10:36,673 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/wandb-summary.json
2024-03-28 18:10:37,678 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/output.log
2024-03-28 18:10:37,863 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:10:41,659 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 18:10:41,659 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: stop_status
2024-03-28 18:10:41,662 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 18:10:43,838 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:10:48,736 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: partial_history
2024-03-28 18:10:48,737 DEBUG   SenderThread:80421 [sender.py:send():382] send: history
2024-03-28 18:10:48,737 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: summary_record
2024-03-28 18:10:48,738 INFO    SenderThread:80421 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-28 18:10:49,736 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/wandb-summary.json
2024-03-28 18:10:49,742 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:10:51,748 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/output.log
2024-03-28 18:10:54,767 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:10:55,750 DEBUG   SystemMonitor:80421 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-03-28 18:10:55,752 DEBUG   SenderThread:80421 [sender.py:send():382] send: telemetry
2024-03-28 18:10:55,753 DEBUG   SenderThread:80421 [sender.py:send():382] send: stats
2024-03-28 18:10:56,664 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 18:10:56,664 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: stop_status
2024-03-28 18:10:56,667 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 18:10:59,797 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:11:00,561 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: partial_history
2024-03-28 18:11:00,562 DEBUG   SenderThread:80421 [sender.py:send():382] send: history
2024-03-28 18:11:00,562 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: summary_record
2024-03-28 18:11:00,563 INFO    SenderThread:80421 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-28 18:11:00,784 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/config.yaml
2024-03-28 18:11:00,784 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/wandb-summary.json
2024-03-28 18:11:01,789 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/output.log
2024-03-28 18:11:05,582 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:11:10,600 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:11:11,666 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 18:11:11,667 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: stop_status
2024-03-28 18:11:11,672 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 18:11:15,501 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: partial_history
2024-03-28 18:11:15,502 DEBUG   SenderThread:80421 [sender.py:send():382] send: history
2024-03-28 18:11:15,503 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: summary_record
2024-03-28 18:11:15,503 INFO    SenderThread:80421 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-28 18:11:15,853 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/wandb-summary.json
2024-03-28 18:11:16,507 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:11:17,863 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/output.log
2024-03-28 18:11:21,523 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:11:25,754 DEBUG   SenderThread:80421 [sender.py:send():382] send: stats
2024-03-28 18:11:25,850 ERROR   FileStreamThread:80421 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/lisp/propagation-CLtargetprop/ob07yjgb/file_stream
NoneType: None
2024-03-28 18:11:26,667 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:11:26,671 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 18:11:26,672 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: stop_status
2024-03-28 18:11:26,677 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 18:11:28,840 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: partial_history
2024-03-28 18:11:28,841 DEBUG   SenderThread:80421 [sender.py:send():382] send: history
2024-03-28 18:11:28,842 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: summary_record
2024-03-28 18:11:28,842 INFO    SenderThread:80421 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-28 18:11:28,911 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/wandb-summary.json
2024-03-28 18:11:29,916 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/output.log
2024-03-28 18:11:31,851 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:11:36,872 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:11:39,122 ERROR   FileStreamThread:80421 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/lisp/propagation-CLtargetprop/ob07yjgb/file_stream
NoneType: None
2024-03-28 18:11:40,637 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: partial_history
2024-03-28 18:11:40,638 DEBUG   SenderThread:80421 [sender.py:send():382] send: history
2024-03-28 18:11:40,638 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: summary_record
2024-03-28 18:11:40,639 INFO    SenderThread:80421 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-28 18:11:40,971 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/wandb-summary.json
2024-03-28 18:11:41,676 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 18:11:41,677 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: stop_status
2024-03-28 18:11:41,682 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 18:11:42,835 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:11:43,981 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/output.log
2024-03-28 18:11:47,859 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:11:52,881 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:11:53,148 ERROR   FileStreamThread:80421 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/lisp/propagation-CLtargetprop/ob07yjgb/file_stream
NoneType: None
2024-03-28 18:11:53,928 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: partial_history
2024-03-28 18:11:53,929 DEBUG   SenderThread:80421 [sender.py:send():382] send: history
2024-03-28 18:11:53,929 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: summary_record
2024-03-28 18:11:53,930 INFO    SenderThread:80421 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-28 18:11:54,024 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/wandb-summary.json
2024-03-28 18:11:55,759 DEBUG   SenderThread:80421 [sender.py:send():382] send: stats
2024-03-28 18:11:56,035 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/output.log
2024-03-28 18:11:56,682 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 18:11:56,682 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: stop_status
2024-03-28 18:11:56,685 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 18:11:58,800 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:12:03,815 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:12:04,812 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: partial_history
2024-03-28 18:12:04,813 DEBUG   SenderThread:80421 [sender.py:send():382] send: history
2024-03-28 18:12:04,813 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: summary_record
2024-03-28 18:12:04,814 INFO    SenderThread:80421 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-28 18:12:04,897 ERROR   FileStreamThread:80421 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/lisp/propagation-CLtargetprop/ob07yjgb/file_stream
NoneType: None
2024-03-28 18:12:05,073 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/wandb-summary.json
2024-03-28 18:12:08,091 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/output.log
2024-03-28 18:12:08,828 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:12:11,687 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: stop_status
2024-03-28 18:12:11,687 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: stop_status
2024-03-28 18:12:11,689 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 18:12:14,803 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:12:16,593 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: partial_history
2024-03-28 18:12:16,593 DEBUG   SenderThread:80421 [sender.py:send():382] send: history
2024-03-28 18:12:16,594 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: summary_record
2024-03-28 18:12:16,595 INFO    SenderThread:80421 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-28 18:12:16,613 DEBUG   SenderThread:80421 [sender.py:send():382] send: exit
2024-03-28 18:12:16,613 INFO    SenderThread:80421 [sender.py:send_exit():589] handling exit code: 1
2024-03-28 18:12:16,613 INFO    SenderThread:80421 [sender.py:send_exit():591] handling runtime: 140
2024-03-28 18:12:16,614 INFO    SenderThread:80421 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-28 18:12:16,614 INFO    SenderThread:80421 [sender.py:send_exit():597] send defer
2024-03-28 18:12:16,614 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: defer
2024-03-28 18:12:16,614 INFO    HandlerThread:80421 [handler.py:handle_request_defer():172] handle defer: 0
2024-03-28 18:12:16,614 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: defer
2024-03-28 18:12:16,614 INFO    SenderThread:80421 [sender.py:send_request_defer():613] handle sender defer: 0
2024-03-28 18:12:16,614 INFO    SenderThread:80421 [sender.py:transition_state():617] send defer: 1
2024-03-28 18:12:16,614 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: defer
2024-03-28 18:12:16,614 INFO    HandlerThread:80421 [handler.py:handle_request_defer():172] handle defer: 1
2024-03-28 18:12:16,614 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: defer
2024-03-28 18:12:16,614 INFO    SenderThread:80421 [sender.py:send_request_defer():613] handle sender defer: 1
2024-03-28 18:12:16,615 INFO    SenderThread:80421 [sender.py:transition_state():617] send defer: 2
2024-03-28 18:12:16,615 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: defer
2024-03-28 18:12:16,615 INFO    HandlerThread:80421 [handler.py:handle_request_defer():172] handle defer: 2
2024-03-28 18:12:16,615 INFO    HandlerThread:80421 [system_monitor.py:finish():203] Stopping system monitor
2024-03-28 18:12:16,615 DEBUG   SystemMonitor:80421 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-03-28 18:12:16,615 INFO    HandlerThread:80421 [interfaces.py:finish():202] Joined cpu monitor
2024-03-28 18:12:16,615 DEBUG   SystemMonitor:80421 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-03-28 18:12:16,615 INFO    HandlerThread:80421 [interfaces.py:finish():202] Joined disk monitor
2024-03-28 18:12:16,616 INFO    HandlerThread:80421 [interfaces.py:finish():202] Joined gpuapple monitor
2024-03-28 18:12:16,616 INFO    HandlerThread:80421 [interfaces.py:finish():202] Joined memory monitor
2024-03-28 18:12:16,616 INFO    HandlerThread:80421 [interfaces.py:finish():202] Joined network monitor
2024-03-28 18:12:16,616 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: defer
2024-03-28 18:12:16,616 INFO    SenderThread:80421 [sender.py:send_request_defer():613] handle sender defer: 2
2024-03-28 18:12:16,616 INFO    SenderThread:80421 [sender.py:transition_state():617] send defer: 3
2024-03-28 18:12:16,616 DEBUG   SenderThread:80421 [sender.py:send():382] send: stats
2024-03-28 18:12:16,616 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: defer
2024-03-28 18:12:16,616 INFO    HandlerThread:80421 [handler.py:handle_request_defer():172] handle defer: 3
2024-03-28 18:12:16,617 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: defer
2024-03-28 18:12:16,617 INFO    SenderThread:80421 [sender.py:send_request_defer():613] handle sender defer: 3
2024-03-28 18:12:16,617 INFO    SenderThread:80421 [sender.py:transition_state():617] send defer: 4
2024-03-28 18:12:16,617 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: defer
2024-03-28 18:12:16,617 INFO    HandlerThread:80421 [handler.py:handle_request_defer():172] handle defer: 4
2024-03-28 18:12:16,617 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: defer
2024-03-28 18:12:16,617 INFO    SenderThread:80421 [sender.py:send_request_defer():613] handle sender defer: 4
2024-03-28 18:12:16,617 INFO    SenderThread:80421 [sender.py:transition_state():617] send defer: 5
2024-03-28 18:12:16,617 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: defer
2024-03-28 18:12:16,617 INFO    HandlerThread:80421 [handler.py:handle_request_defer():172] handle defer: 5
2024-03-28 18:12:16,617 DEBUG   SenderThread:80421 [sender.py:send():382] send: summary
2024-03-28 18:12:16,618 INFO    SenderThread:80421 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-28 18:12:16,618 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: defer
2024-03-28 18:12:16,618 INFO    SenderThread:80421 [sender.py:send_request_defer():613] handle sender defer: 5
2024-03-28 18:12:16,618 INFO    SenderThread:80421 [sender.py:transition_state():617] send defer: 6
2024-03-28 18:12:16,618 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: defer
2024-03-28 18:12:16,618 INFO    HandlerThread:80421 [handler.py:handle_request_defer():172] handle defer: 6
2024-03-28 18:12:16,618 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: defer
2024-03-28 18:12:16,618 INFO    SenderThread:80421 [sender.py:send_request_defer():613] handle sender defer: 6
2024-03-28 18:12:16,618 INFO    SenderThread:80421 [sender.py:transition_state():617] send defer: 7
2024-03-28 18:12:16,618 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: status_report
2024-03-28 18:12:16,618 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: defer
2024-03-28 18:12:16,618 INFO    HandlerThread:80421 [handler.py:handle_request_defer():172] handle defer: 7
2024-03-28 18:12:16,619 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: defer
2024-03-28 18:12:16,619 INFO    SenderThread:80421 [sender.py:send_request_defer():613] handle sender defer: 7
2024-03-28 18:12:16,675 ERROR   FileStreamThread:80421 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/lisp/propagation-CLtargetprop/ob07yjgb/file_stream
NoneType: None
2024-03-28 18:12:17,126 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/wandb-summary.json
2024-03-28 18:12:17,618 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-28 18:12:18,132 INFO    Thread-12 :80421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/output.log
2024-03-28 18:12:18,619 INFO    SenderThread:80421 [sender.py:transition_state():617] send defer: 8
2024-03-28 18:12:18,619 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: poll_exit
2024-03-28 18:12:18,619 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: defer
2024-03-28 18:12:18,619 INFO    HandlerThread:80421 [handler.py:handle_request_defer():172] handle defer: 8
2024-03-28 18:12:18,619 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: defer
2024-03-28 18:12:18,619 INFO    SenderThread:80421 [sender.py:send_request_defer():613] handle sender defer: 8
2024-03-28 18:12:18,620 INFO    SenderThread:80421 [job_builder.py:build():296] Attempting to build job artifact
2024-03-28 18:12:18,620 INFO    SenderThread:80421 [job_builder.py:_get_source_type():426] is repo sourced job
2024-03-28 18:12:18,624 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-28 18:12:18,640 INFO    SenderThread:80421 [job_builder.py:build():402] adding wandb-job metadata file
2024-03-28 18:12:18,643 INFO    SenderThread:80421 [sender.py:transition_state():617] send defer: 9
2024-03-28 18:12:18,643 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: poll_exit
2024-03-28 18:12:18,643 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: defer
2024-03-28 18:12:18,643 DEBUG   SenderThread:80421 [sender.py:send():382] send: artifact
2024-03-28 18:12:18,643 INFO    HandlerThread:80421 [handler.py:handle_request_defer():172] handle defer: 9
2024-03-28 18:12:19,051 ERROR   SenderThread:80421 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-03-28 18:12:19,052 ERROR   SenderThread:80421 [internal_api.py:execute():374] {"errors":[{"message":"failed to find run propagation-CLtargetprop/ob07yjgb","path":["createArtifactManifest"]}],"data":{"createArtifactManifest":null}}
2024-03-28 18:12:19,053 ERROR   SenderThread:80421 [sender.py:send_artifact():1496] send_artifact: failed for artifact "job/job-https___github.com_emmagg6_propagation.git_CLtargetprop_main.py": It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-03-28 18:12:19,054 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: defer
2024-03-28 18:12:19,054 INFO    SenderThread:80421 [sender.py:send_request_defer():613] handle sender defer: 9
2024-03-28 18:12:19,054 INFO    SenderThread:80421 [dir_watcher.py:finish():358] shutting down directory watcher
2024-03-28 18:12:19,138 INFO    SenderThread:80421 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/output.log
2024-03-28 18:12:19,138 INFO    SenderThread:80421 [dir_watcher.py:finish():388] scan: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files
2024-03-28 18:12:19,138 INFO    SenderThread:80421 [dir_watcher.py:finish():402] scan save: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/requirements.txt requirements.txt
2024-03-28 18:12:19,138 INFO    SenderThread:80421 [dir_watcher.py:finish():402] scan save: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/output.log output.log
2024-03-28 18:12:19,141 INFO    SenderThread:80421 [dir_watcher.py:finish():402] scan save: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/config.yaml config.yaml
2024-03-28 18:12:19,143 INFO    SenderThread:80421 [dir_watcher.py:finish():402] scan save: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/wandb-summary.json wandb-summary.json
2024-03-28 18:12:19,146 INFO    SenderThread:80421 [dir_watcher.py:finish():402] scan save: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/conda-environment.yaml conda-environment.yaml
2024-03-28 18:12:19,149 INFO    SenderThread:80421 [dir_watcher.py:finish():402] scan save: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/wandb-metadata.json wandb-metadata.json
2024-03-28 18:12:19,149 INFO    SenderThread:80421 [sender.py:transition_state():617] send defer: 10
2024-03-28 18:12:19,151 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: defer
2024-03-28 18:12:19,152 INFO    HandlerThread:80421 [handler.py:handle_request_defer():172] handle defer: 10
2024-03-28 18:12:19,152 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: defer
2024-03-28 18:12:19,152 INFO    SenderThread:80421 [sender.py:send_request_defer():613] handle sender defer: 10
2024-03-28 18:12:19,152 INFO    SenderThread:80421 [file_pusher.py:finish():172] shutting down file pusher
2024-03-28 18:12:19,230 ERROR   wandb-upload_1:80421 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-03-28 18:12:19,230 ERROR   wandb-upload_1:80421 [internal_api.py:execute():374] {"errors":[{"message":"run propagation-CLtargetprop/ob07yjgb not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-03-28 18:12:19,230 ERROR   Thread-11 :80421 [step_upload.py:_handle_event():200] Failed to upload file: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/output.log
Traceback (most recent call last):
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2384, in upload_urls
    query_result = self.gql(
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/util.py", line 907, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-03-28 18:12:19,231 ERROR   wandb-upload_0:80421 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-03-28 18:12:19,236 ERROR   wandb-upload_0:80421 [internal_api.py:execute():374] {"errors":[{"message":"run propagation-CLtargetprop/ob07yjgb not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-03-28 18:12:19,236 ERROR   Thread-11 :80421 [step_upload.py:_handle_event():200] Failed to upload file: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/requirements.txt
Traceback (most recent call last):
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2384, in upload_urls
    query_result = self.gql(
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/util.py", line 907, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-03-28 18:12:19,338 ERROR   wandb-upload_3:80421 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-03-28 18:12:19,338 ERROR   wandb-upload_3:80421 [internal_api.py:execute():374] {"errors":[{"message":"run propagation-CLtargetprop/ob07yjgb not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-03-28 18:12:19,338 ERROR   Thread-11 :80421 [step_upload.py:_handle_event():200] Failed to upload file: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/wandb-summary.json
Traceback (most recent call last):
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2384, in upload_urls
    query_result = self.gql(
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/util.py", line 907, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-03-28 18:12:19,342 ERROR   wandb-upload_2:80421 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-03-28 18:12:19,342 ERROR   wandb-upload_2:80421 [internal_api.py:execute():374] {"errors":[{"message":"run propagation-CLtargetprop/ob07yjgb not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-03-28 18:12:19,342 ERROR   Thread-11 :80421 [step_upload.py:_handle_event():200] Failed to upload file: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/config.yaml
Traceback (most recent call last):
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2384, in upload_urls
    query_result = self.gql(
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/util.py", line 907, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-03-28 18:12:19,349 ERROR   wandb-upload_4:80421 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-03-28 18:12:19,349 ERROR   wandb-upload_4:80421 [internal_api.py:execute():374] {"errors":[{"message":"run propagation-CLtargetprop/ob07yjgb not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-03-28 18:12:19,349 ERROR   Thread-11 :80421 [step_upload.py:_handle_event():200] Failed to upload file: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/files/conda-environment.yaml
Traceback (most recent call last):
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2384, in upload_urls
    query_result = self.gql(
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/wandb/util.py", line 907, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-03-28 18:12:19,555 INFO    Thread-11 :80421 [sender.py:transition_state():617] send defer: 11
2024-03-28 18:12:19,555 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: defer
2024-03-28 18:12:19,555 INFO    HandlerThread:80421 [handler.py:handle_request_defer():172] handle defer: 11
2024-03-28 18:12:19,555 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: defer
2024-03-28 18:12:19,555 INFO    SenderThread:80421 [sender.py:send_request_defer():613] handle sender defer: 11
2024-03-28 18:12:19,555 INFO    SenderThread:80421 [file_pusher.py:join():178] waiting for file pusher
2024-03-28 18:12:19,557 INFO    SenderThread:80421 [sender.py:transition_state():617] send defer: 12
2024-03-28 18:12:19,557 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: defer
2024-03-28 18:12:19,557 INFO    HandlerThread:80421 [handler.py:handle_request_defer():172] handle defer: 12
2024-03-28 18:12:19,557 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: defer
2024-03-28 18:12:19,557 INFO    SenderThread:80421 [sender.py:send_request_defer():613] handle sender defer: 12
2024-03-28 18:12:19,557 INFO    SenderThread:80421 [file_stream.py:finish():595] file stream finish called
2024-03-28 18:12:19,629 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-28 18:12:19,637 ERROR   FileStreamThread:80421 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/lisp/propagation-CLtargetprop/ob07yjgb/file_stream
NoneType: None
2024-03-28 18:12:19,722 INFO    SenderThread:80421 [file_stream.py:finish():599] file stream finish is done
2024-03-28 18:12:19,722 INFO    SenderThread:80421 [sender.py:transition_state():617] send defer: 13
2024-03-28 18:12:19,722 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: poll_exit
2024-03-28 18:12:19,722 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: defer
2024-03-28 18:12:19,722 INFO    HandlerThread:80421 [handler.py:handle_request_defer():172] handle defer: 13
2024-03-28 18:12:19,723 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: defer
2024-03-28 18:12:19,723 INFO    SenderThread:80421 [sender.py:send_request_defer():613] handle sender defer: 13
2024-03-28 18:12:19,723 INFO    SenderThread:80421 [sender.py:transition_state():617] send defer: 14
2024-03-28 18:12:19,723 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: defer
2024-03-28 18:12:19,724 DEBUG   SenderThread:80421 [sender.py:send():382] send: final
2024-03-28 18:12:19,724 DEBUG   SenderThread:80421 [sender.py:send():382] send: footer
2024-03-28 18:12:19,724 INFO    HandlerThread:80421 [handler.py:handle_request_defer():172] handle defer: 14
2024-03-28 18:12:19,724 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: defer
2024-03-28 18:12:19,724 INFO    SenderThread:80421 [sender.py:send_request_defer():613] handle sender defer: 14
2024-03-28 18:12:19,725 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-28 18:12:19,725 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-28 18:12:19,726 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: poll_exit
2024-03-28 18:12:19,726 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: server_info
2024-03-28 18:12:19,726 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: poll_exit
2024-03-28 18:12:19,726 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: get_summary
2024-03-28 18:12:19,727 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: server_info
2024-03-28 18:12:19,727 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: sampled_history
2024-03-28 18:12:19,729 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-28 18:12:19,729 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: job_info
2024-03-28 18:12:19,836 DEBUG   SenderThread:80421 [sender.py:send_request():409] send_request: job_info
2024-03-28 18:12:19,837 INFO    MainThread:80421 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-28 18:12:19,837 INFO    MainThread:80421 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-28 18:12:19,837 INFO    MainThread:80421 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-03-28 18:12:19,837 DEBUG   HandlerThread:80421 [handler.py:handle_request():146] handle_request: shutdown
2024-03-28 18:12:19,837 INFO    HandlerThread:80421 [handler.py:finish():869] shutting down handler
2024-03-28 18:12:20,735 INFO    WriterThread:80421 [datastore.py:close():296] close: /Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/wandb/run-20240328_180955-ob07yjgb/run-ob07yjgb.wandb
2024-03-28 18:12:20,842 INFO    SenderThread:80421 [sender.py:finish():1572] shutting down sender
2024-03-28 18:12:20,842 INFO    SenderThread:80421 [file_pusher.py:finish():172] shutting down file pusher
2024-03-28 18:12:20,842 INFO    SenderThread:80421 [file_pusher.py:join():178] waiting for file pusher
